### ISSUE TITLE
Allow passing in exceptions to the encode function

### ISSUE THREAD

**Issue by jschniper** [devinus/poison#104]
I figure there is probably a good reason for not allowing this but I've been looking for a way to pass in exceptions to the encode function.

My case is something like the following
```
map = %{
    key1: "val1",
    key2: "val2
}
```

and I'd like to be able to sometimes exclude a key using something along the lines of `Poison.encode!(map, except: [:key1])`

I'm happy to work on this and provide a pull request but I wanted to make sure I wasn't heading down a bad path first.

**Comment by ericmj** [comment]
You can remove the key before calling encode: `map |> Map.drop([:key1]) |> Poison.encode`.

**Comment by jschniper** [comment]
I'm using a struct and I know I can still just do `struct |> Map.from_struct |> Map.drop([:key1])` but it seems somewhat inconsistent to include an except in the protocol but not allow something similar in the standard encode method.

This absolutely falls under syntactical sugar which is why I'm asking.

**Comment by ericmj** [comment]
You don't have to call `Map.from_struct`.

> [...] it seems somewhat inconsistent to include an except in the protocol but not allow something similar in the standard encode function.

Because that's the only way to remove keys when deriving the protocol, no functions are available there.

I am generally against these kind of syntactical changes to Poison that can also be solved with a single function call. Poison is used by 1/6th of all packages on Hex.pm and tries very hard to achieve good performance. Every option like this will slightly degrade the performance for everyone and most projects will not need it.

**Comment by jschniper** [comment]
Okay, makes perfect sense. And I wasn't even thinking about the fact that Poison calls `Map.from_struct` for me. Thank you for the answers
