### ISSUE TITLE
Poison.Decode.decode doesn't use defaults when decodable has atom keys

### ISSUE THREAD

**Issue by blatyo** [devinus/poison#79]
The title is a mouthful, but I think this code example will explain better.

``` elixir
defmodule X do
  defstruct y: 1,
            z: 2
end

Poison.Decode.decode(%{y: 3}, as: %X{}, keys: :atoms!) # => %X{y: 3, z: nil}
Poison.Decode.decode(%{"y" => 3}, as: %X{}) # => %X{y: 3, z: 2}
```

The expectation would be that the first `decode` would have the same result as the second.

**Comment by BennyHallett** [comment]
Hey @blatyo - I just checked this one out and it appears that this behaviour is intentional. There's a test for it here - https://github.com/devinus/poison/blob/master/test/poison/decoder_test.exs#L70

I've had a look and it's not too difficult to change anyway. Happy to submit a PR for it if you think it's the right change to make @devinus

**Comment by blatyo** [comment]
@BennyHallett in that code, it explicitly passes `"age" => nil`. Notice in my example, I don't pass a value for `z`, which is why I expect it to use the default. If I had passed `z: nil`, I wouldn't expect the default to apply.

**Comment by BennyHallett** [comment]
Ah I see - sorry.

That makes it more interesting - I can look further into this.

**Comment by blatyo** [comment]
Thanks guys
