### ISSUE TITLE
keys: :atoms! sometime tries to convert values to keys

### ISSUE THREAD

**Issue by aarvay** [devinus/poison#92]
I've an example that when fed to `Poison.decode!` with `keys: :atoms!` option, errors out with `ArgumentError` where it tried converting a value to atom (which wouldn't be initialised of course)

It seems to be just a rare anomaly, because I wasn't able to reproduce the error with a simpler example. Am I missing something here?

[This gist](https://gist.github.com/aarvay/7412f70a4de6a2e256bc82130804da1a) contains the example that triggers this anomaly.

Using poison v2.2.0

**Comment by rschmukler** [comment]
The `keys: :atoms!` errors if the JSON contains atoms that haven't yet been initialized. In the example you linked, the following atoms have never been declared, but do appear in the JSON: `:captured, :card_id, :bank, :wallet`.

If you want the atoms to be declared, you can use `keys: :atoms`. Otherwise, your code works if you declare the atoms first. ie.

```
iex> [:captured, :card_id, :bank, :wallet]
#=> [:captured, :card_id, :bank, :wallet]
PoisonAnomaly.run
```

**Comment by aarvay** [comment]
Closing this issue because it's not actually one. I assumed `captured` is coming from the value of the status field. Didn't expect that as a separate key. (The response is from a payment gateway) Opened the issue in a hurry without thoroughly checking the response. Thanks @rschmukler for pointing it out
